export const books = [
  {
    id: 1,
    title: "Crack the Coding Interview",
    author: "Gayle Laakmann McDowell",
    genre: "Technology",
    description: "189 programming interview questions and solutions covering data structures, algorithms, and system design.",
    url: "https://m.media-amazon.com/images/I/61mIq2iJUXL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
    pages: 687,
    publishedYear: 2015,
    inStock: true,
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Help",
    description: "A proven framework for building good habits and breaking bad ones, one tiny change at a time.",
    url: "https://m.media-amazon.com/images/I/81ANaVZk5LL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
    pages: 320,
    publishedYear: 2018,
    inStock: true,
  },
  {
    id: 3,
    title: "Can't Hurt Me",
    author: "David Goggins",
    genre: "Memoir",
    description: "A former Navy SEAL's account of overcoming adversity through mental toughness.",
    url: "https://m.media-amazon.com/images/I/81gTRv2HXrL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
    pages: 364,
    publishedYear: 2018,
    inStock: true,
  },
  {
    id: 4,
    title: "Deep Work",
    author: "Cal Newport",
    genre: "Productivity",
    description: "Rules for focused success in a distracted world.",
    url: "https://m.media-amazon.com/images/I/91nujEwIpYL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
    pages: 304,
    publishedYear: 2016,
    inStock: true,
  },
  {
    id: 5,
    title: "The 10X Rule",
    author: "Grant Cardone",
    genre: "Business",
    description: "The only difference between success and failure is the amount of massive action you take.",
    url: "https://m.media-amazon.com/images/I/71hjq42hvGL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
    pages: 240,
    publishedYear: 2011,
    inStock: true,
  },
  {
    id: 6,
    title: "Sell Or Be Sold",
    author: "Grant Cardone",
    genre: "Business",
    description: "How to get your way in business and in life through the fundamentals of selling.",
    url: "https://m.media-amazon.com/images/I/616OvChM3RL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
    pages: 279,
    publishedYear: 2011,
    inStock: true,
  },
  {
    id: 7,
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    genre: "Finance",
    description: "What the rich teach their kids about money that the poor and middle class do not.",
    url: "https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
    pages: 336,
    publishedYear: 1997,
    inStock: true,
  },
  {
    id: 8,
    title: "Cashflow Quadrant",
    author: "Robert Kiyosaki",
    genre: "Finance",
    description: "Rich dad's guide to financial freedom, exploring the four paths to income.",
    url: "https://m.media-amazon.com/images/I/71+SWQ6xj1L._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
    pages: 288,
    publishedYear: 1998,
    inStock: true,
  },
  {
    id: 9,
    title: "48 Laws of Power Summary",
    author: "Robert Greene",
    genre: "Philosophy",
    description: "A condensed guide to the 48 laws of power, strategy, and influence.",
    url: "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
    pages: 452,
    publishedYear: 1998,
    inStock: false,
  },
  {
    id: 10,
    title: "The 5 Second Rule",
    author: "Mel Robbins",
    genre: "Self-Help",
    description: "Transform your life, work, and confidence with everyday courage.",
    url: "https://m.media-amazon.com/images/I/91wOERyhh7L._UF1000,1000_QL80_.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
    pages: 238,
    publishedYear: 2017,
    inStock: true,
  },
  {
    id: 11,
    title: "How to Win Friends & Influence People",
    author: "Dale Carnegie",
    genre: "Self-Help",
    description: "Timeless principles for improving relationships and personal influence.",
    url: "https://m.media-amazon.com/images/I/71vK0WVQ4rL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
    pages: 291,
    publishedYear: 1936,
    inStock: true,
  },
  {
    id: 12,
    title: "Mastery",
    author: "Robert Greene",
    genre: "Philosophy",
    description: "An exploration of the path to mastery through historical and contemporary case studies.",
    url: "https://m.media-amazon.com/images/I/51V3121nmkL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
    pages: 320,
    publishedYear: 2012,
    inStock: true,
  },
  {
    id: 13,
    title: "The Lean Startup",
    author: "Eric Ries",
    genre: "Business",
    description: "How today's entrepreneurs use continuous innovation to create radically successful businesses.",
    url: "https://m.media-amazon.com/images/I/81vaXFqEcdL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 27,
    salePrice: 15.5,
    rating: 4.5,
    pages: 336,
    publishedYear: 2011,
    inStock: true,
  },
  {
    id: 14,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    genre: "Psychology",
    description: "A groundbreaking exploration of the two systems that drive the way we think.",
    url: "https://m.media-amazon.com/images/I/71dGZgb7lYL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 4.5,
    pages: 499,
    publishedYear: 2011,
    inStock: true,
  },
  {
    id: 15,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    genre: "Self-Help",
    description: "A counterintuitive approach to living a good life by caring about what truly matters.",
    url: "https://m.media-amazon.com/images/I/71QKQ9mwV7L._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 27,
    salePrice: 13.99,
    rating: 4,
    pages: 224,
    publishedYear: 2016,
    inStock: true,
  },
  {
    id: 16,
    title: "Zero to One",
    author: "Peter Thiel",
    genre: "Business",
    description: "Notes on startups, or how to build the future by creating new things rather than copying.",
    url: "https://m.media-amazon.com/images/I/71iozUK+HdL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 28,
    salePrice: 16,
    rating: 4.5,
    pages: 224,
    publishedYear: 2014,
    inStock: false,
  },
  {
    id: 17,
    title: "The Power of Now",
    author: "Eckhart Tolle",
    genre: "Spirituality",
    description: "A guide to spiritual enlightenment through living fully in the present moment.",
    url: "https://m.media-amazon.com/images/I/71xbSVMFwsL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 24,
    salePrice: null,
    rating: 4.5,
    pages: 236,
    publishedYear: 1997,
    inStock: true,
  },
  {
    id: 18,
    title: "Never Split the Difference",
    author: "Chris Voss",
    genre: "Business",
    description: "Negotiating as if your life depended on it, from a former FBI hostage negotiator.",
    url: "https://m.media-amazon.com/images/I/71WZWCXomFL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 18.5,
    rating: 5,
    pages: 288,
    publishedYear: 2016,
    inStock: true,
  },
];